
export const auth = {
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  AUTH_LOGIN_PENDING: 'AUTH_LOGIN_PENDING',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_ERROR: 'AUTH_LOGOUT_ERROR',
  AUTH_LOGOUT_PENDING: 'AUTH_LOGOUT_PENDING',
  AUTH_AUTHORIZE_SUCCESS: 'AUTH_AUTHORIZE_SUCCESS',
  AUTH_AUTHORIZE_ERROR: 'AUTH_AUTHORIZE_ERROR',
  AUTH_AUTHORIZE_PENDING: 'AUTH_AUTHORIZE_PENDING',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_REGISTER_ERROR: 'AUTH_REGISTER_ERROR',
  AUTH_REGISTER_PENDING: 'AUTH_REGISTER_PENDING',
}

export const users = {
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
  GET_USERS_PENDING: 'GET_USERS_PENDING',
}

export const playerList = {
  GET_PLAYER_LIST_SUCCESS: 'GET_PLAYER_LIST_SUCCESS',
  GET_PLAYER_LIST_ERROR: 'GET_PLAYER_LIST_ERROR',
  GET_PLAYER_LIST_PENDING: 'GET_PLAYER_LIST_PENDING',
}

export const playerInformation = {
  GET_PLAYER_INFORMATION_SUCCESS: 'GET_PLAYER_INFORMATION_SUCCESS',
  GET_PLAYER_INFORMATION_ERROR: 'GET_PLAYER_INFORMATION_ERROR',
  GET_PLAYER_INFORMATION_PENDING: 'GET_PLAYER_INFORMATION_PENDING',
}
